# Generated by Django 4.1.2 on 2023-05-11 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('tech', models.CharField(blank=True, choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('APP DEVELOPMENT', 'APP DEVELOPMENT'), ('MACHINE LEARNING', 'MACHINE LEARNING'), ('DJANGO', 'DJANGO'), ('REACTJS', 'REACTJS'), ('NODEJS', 'NODEJS'), ('FLUTTER', 'FLUTTER'), ('KOTLIN', 'KOTLIN'), ('PYTHON', 'PYTHON'), ('OTHERS', 'OTHERS')], max_length=18, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Community_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.community_questions')),
            ],
        ),
    ]
