# Generated by Django 4.1.2 on 2023-05-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community_Questions',
            new_name='Blogs',
        ),
        migrations.DeleteModel(
            name='Community_Answers',
        ),
    ]
